version: '2'
services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER_NAME: 'root'
  datanutorg:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/datanutorg"

    ports:
      - "3000:3000"
    depends_on:
      - database
